# defaults
SIM ?= icarus
TOPLEVEL_LANG ?= verilog

VERILOG_SOURCES += $(PWD)/a3000_rom_emulator.v

# TOPLEVEL is the name of the toplevel module in your Verilog or VHDL file
TOPLEVEL = a3000_rom_emulator

# MODULE is the basename of the Python test file
MODULE = arcflash_test

# include cocotb's make rules to take care of the simulator setup
include $(shell cocotb-config --makefiles)/Makefile.sim
