#!/usr/bin/python

# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# --------------------------
# fx2_tube_cartridge_adapter
# --------------------------

# by Phillip Pearson

# Adapter board to make it easy to connect an LCSoft Mini board to either an
# Acorn Electron via a Plus 1 cartridge slot, or a BBC Micro or BBC Master via
# the Tube connector, to run Sigrok and David Banks' decode6502 software.

# This also allows connecting a Raspberry Pi running PiTubeDirect to a BBC or
# Electron.  When connected to an Electron, it drives the /TUBE line low on the
# Pi when &FCEx addresses are being accessed (i.e. nINFC='0' and A7:4 = x"E").
# When connected to a BBC, it just buffers the /TUBE line from the Tube
# connetor.


# DONE add a second tube header so BBC folks can pass signals through to a 5V
# tube device and debug the Tube connection.  DECISION: skip this, because a
# two-drive IDE cable will allow putting the board inline with a Tube device
# anyway.

# DONE hook up both bbc_nTUBE and tube_nTUBE to the CPLD, to allow using a Pi on
# a BBC or Master.

# TODO add jumpers from 3V3_PI and 3V3_FX2 to 3V3, to allow not populating the regulator

# TODO put a resistor in series with the /TUBE line, in case the CPLD is driving
# it when we're connected to a BBC.  Also add in a jumper to disconnect it
# entirely.

# TODO think about whether we can autodetect stuff (by averaging over a few
# clocks...)

# TODO remove /RESET from the CPLD and use a schottky diode + pullup to convert
# that down to 3v3.  It's a slow signal (generated by the keyboard) so it
# doesn't need to go through the CPLD.

# DONE figure out if it's easier to put the tube connector on the same side of
# the board as the cartridge interface -- if it makes the wiring easier or
# harder.  it probably looks nicest up top.  DECISION: next to the cartridge
# interface; otherwise this gets way too complicated.

# DONE Trivial, possibly pointless addition: This can also double as a very
# simple Tube adapter for the Electron, when logic is fitted to match the Tube
# addresses and generate the /TUBE signal).  DECISION: going a bit further and
# making it a PiTubeDirect adapter too.

# DONE check AP6 thread on stardot to see if external tube devices require a
# buffered clock.  If so, there's no point doing this simple option.  DECISION:
# adding a buffered clock because the logic analyzer needs it on the Electron.

# ARCHIVE: not doing this any more; just using a CPLD:

    # nTUBE <= '0' when nINFC = '0' and A(7 downto 4) = x"E" else '1'

    # i.e. nTUBE = !(!nINFC and A7 and A6 and A5 and !A4)
    #            = (((nINFC nand 1) and (A4 nand 1)) and (A7 and A6)) nand (A5)

    # A 74HCT00 for the nands and a 74HCT08 for the ands should do this nicely.

    # nand0 = nINFC nand 1 (= !nINFC)
    # nand1 = A4 nand 1 (= !A4)
    # and0 = nand0 and nand1 (= !nINFC and !A4)
    # and1 = A7 and A6
    # and2 = and0 and and1 (= !nINFC and A7 and A6 and !A4)
    # nTUBE = nand2 = and2 nand A5 (= !(!nINFC and A7 and A6 and A5 and !A4))
    # - 74hct00 + capacitor
    # - 74hct08 + capacitor
    # - 330R/1k output resistor on nTUBE to limit current if plugged into both
    # Electron and BBC for some reason.

import sys, os
here = os.path.dirname(sys.argv[0])
sys.path.insert(0, os.path.join(here, "../../third_party/myelin-kicad.pretty"))
import myelin_kicad_pcb
Pin = myelin_kicad_pcb.Pin


# Cartridge connector
cart_front = myelin_kicad_pcb.Component(
    footprint="myelin-kicad:acorn_electron_cartridge_edge_connector",
    identifier="CART",
    value="edge connector",
    pins=[
        # front of cartridge / bottom layer of PCB
        Pin( "B1", "5V",    "5V"),
        Pin( "B2", "A10"),
        Pin( "B3", "D3",    "cpu_D3"),
        Pin( "B4", "A11"),
        Pin( "B5", "A9"),
        Pin( "B6", "D7",    "cpu_D7"),
        Pin( "B7", "D6",    "cpu_D6"),
        Pin( "B8", "D5",    "cpu_D5"),
        Pin( "B9", "D4",    "cpu_D4"),
        Pin("B10", "nOE2"),
        Pin("B11", "BA7",   "cpu_A7"),
        Pin("B12", "BA6",   "cpu_A6"),
        Pin("B13", "BA5",   "cpu_A5"),
        Pin("B14", "BA4",   "cpu_A4"),
        Pin("B15", "BA3",   "cpu_A3"),
        Pin("B16", "BA2",   "cpu_A2"),
        Pin("B17", "BA1",   "cpu_A1"),
        Pin("B18", "BA0",   "cpu_A0"),
        Pin("B19", "D0",    "cpu_D0"),
        Pin("B20", "D2",    "cpu_D2"),
        Pin("B21", "D1",    "cpu_D1"),
        Pin("B22", "GND",   "GND"),
        # rear of cartridge / top layer of PCB
        Pin( "A1", "5V",    "5V"),
        Pin( "A2", "nOE"),
        Pin( "A3", "nRST",  "cpu_nRST"),
        Pin( "A4", "RnW",   "cpu_RnW"),
        Pin( "A5", "A8"),
        Pin( "A6", "A13"),
        Pin( "A7", "A12"),
        Pin( "A8", "PHI0",  "cpu_CLK"),
        Pin( "A9", "-5V"),
        Pin("A10", "NC"),
        Pin("A11", "READY", "cpu_READY"),
        Pin("A12", "nNMI",  "cpu_nNMI"),
        Pin("A13", "nIRQ",  "cpu_nIRQ"),
        Pin("A14", "nINFC", "elk_nINFC"),
        Pin("A15", "nINFD"),
        Pin("A16", "ROMQA"),
        Pin("A17", "16MHZ", "elk_16MHz"),
        Pin("A18", "nROMSTB"),
        Pin("A19", "ADOUT"),
        Pin("A20", "ADGND"),
        Pin("A21", "ADIN"),
        Pin("A22", "GND",   "GND"),
    ],
)

tube = myelin_kicad_pcb.Component(
    footprint="myelin-kicad:header_2x20_100mil",
    identifier="TUBE",
    value="tube",
    pins=[
        Pin( 1, "0V", "GND"),
        Pin( 2, "RnW", "cpu_RnW"),
        Pin( 3, "0V", "GND"),
        Pin( 4, "2MHzE", "cpu_CLK"),
        Pin( 5, "0V", "GND"),
        Pin( 6, "/IRQ", "cpu_nIRQ"),
        Pin( 7, "0V", "GND"),
        Pin( 8, "/TUBE", "bbc_nTUBE"),
        Pin( 9, "0V", "GND"),
        Pin(10, "/RST", "cpu_nRST"),
        Pin(11, "0V", "GND"),
        Pin(12, "D0", "cpu_D0"),
        Pin(13, "0V", "GND"),
        Pin(14, "D1", "cpu_D1"),
        Pin(15, "0V", "GND"),
        Pin(16, "D2", "cpu_D2"),
        Pin(17, "0V", "GND"),
        Pin(18, "D3", "cpu_D3"),
        Pin(19, "0V", "GND"),
        Pin(20, "D4", "cpu_D4"),
        Pin(21, "0V", "GND"),
        Pin(22, "D5", "cpu_D5"),
        Pin(23, "0V", "GND"),
        Pin(24, "D6", "cpu_D6"),
        Pin(25, "0V", "GND"),
        Pin(26, "D7", "cpu_D7"),
        Pin(27, "0V", "GND"),
        Pin(28, "A0", "cpu_A0"),
        Pin(29, "0V", "GND"),
        Pin(30, "A1", "cpu_A1"),
        Pin(31, "+5V", "5V"),
        Pin(32, "A2", "cpu_A2"),
        Pin(33, "+5V", "5V"),
        Pin(34, "A3", "cpu_A3"),
        Pin(35, "+5V", "5V"),
        Pin(36, "A4", "cpu_A4"),
        Pin(37, "+5V", "5V"),
        Pin(38, "A5", "cpu_A5"),
        Pin(39, "+5V", "5V"),
        Pin(40, "A6", "cpu_A6"),
    ],
)

# TODO cpld.  take elk_pi_tube_direct cpld pinout and remove the two /RESET
# pins, and add A3.  not sure what to do with that yet, but it should come in
# handy.

    # 25 pins from the cartridge + tube port
    # minus IRQ, NMI, READY, /RESET, /TUBE = 20
    # 14 pins to the Raspberry Pi
    # total 34, which is exactly what we have

cpld = myelin_kicad_pcb.Component(
    footprint="myelin-kicad:xilinx_vqg44",
    identifier="PL1",
    value="XC9572XL",
    buses=["cpu_A", "cpu_D", "tube_D"],
    pins=[
        Pin(39, "P1.2", "cpu_D3"),
        Pin(40, "P1.5", "cpu_D5"),
        Pin(41, "P1.6", "cpu_RnW"),
        Pin(42, "P1.8", "cpu_D7"),
        Pin(43, "P1.9-GCK1", "cpu_D6"),
        Pin(44, "P1.11-GCK2", "elk_16MHz"),
        Pin( 1, "P1.14-GCK3", "cpu_CLK"),
        Pin( 2, "P1.15", "cpu_D4"),
        Pin( 3, "P1.17", "cpu_A7"),
        Pin( 4, "GND", "GND"),
        Pin( 5, "P3.2", "cpu_A6"),
        Pin( 6, "P3.5", "cpu_A5"),
        Pin( 7, "P3.8", "cpu_A4"),
        Pin( 8, "P3.9", "elk_nINFC"),
        Pin( 9, "TDI", "cpld_TDI"),
        Pin(10, "TMS", "cpld_TMS"),
        Pin(11, "TCK", "cpld_TCK"),
        Pin(12, "P3.11", "cpu_A2"),
        Pin(13, "P3.14", "cpu_A1"),
        Pin(14, "P3.15", "cpu_A0"),
        Pin(15, "VCCINT_3V3", "3V3"),
        Pin(16, "P3.17", "cpu_D0"),
        Pin(17, "GND", "GND"),
        Pin(18, "P3.16", "cpu_D2"),
        Pin(19, "P4.2", "cpu_D1"),
        Pin(20, "P4.5", "tube_CLK"),
        Pin(21, "P4.8", "tube_D3"),
        Pin(22, "P4.11", "tube_D0"),
        Pin(23, "P4.14", "tube_D1"),
        Pin(24, "TDO", "cpld_TDO"),
        Pin(25, "GND", "GND"),
        Pin(26, "VCCIO_2V5_3V3", "3V3"),
        Pin(27, "P4.15", "tube_D7"),
        Pin(28, "P4.17", "tube_D2"),
        Pin(29, "P2.2", "tube_D6"),
        Pin(30, "P2.5", "tube_D4"),
        Pin(31, "P2.6", "tube_D5"),
        Pin(32, "P2.8", "tube_A0"),
        Pin(33, "P2.9-GSR", "tube_nTUBE"),
        Pin(34, "P2.11-GTS2", "tube_RnW"),
        Pin(35, "VCCINT_3V3", "3V3"),
        Pin(36, "P2.14-GTS1", "bbc_nTUBE"),
        Pin(37, "P2.15", "tube_A2"),
        Pin(38, "P2.17", "tube_A1"),
    ],
)
cpld_cap1 = myelin_kicad_pcb.C0805("100n", "3V3", "GND", ref="C1")
cpld_cap2 = myelin_kicad_pcb.C0805("100n", "3V3", "GND", ref="C2")
cpld_cap3 = myelin_kicad_pcb.C0805("1u", "3V3", "GND", ref="C3")
myelin_kicad_pcb.update_xilinx_constraints(cpld, os.path.join(here, "../cpld/constraints.ucf"))

regulator = myelin_kicad_pcb.Component(
    footprint="TO_SOT_Packages_SMD:SOT-89-3",
    identifier="U1",
    value="MCP1700T-3302E/MB",
    pins=[
        Pin(2, "VIN", ["5V"]),
        Pin(3, "VOUT", ["3V3"]),
        Pin(1, "GND", ["GND"]),
    ],
)
reg_in_cap = myelin_kicad_pcb.C0805("1u", "GND", "5V", ref="C4")
reg_out_cap = myelin_kicad_pcb.C0805("1u", "3V3", "GND", ref="C5")

pi_power_jumper = myelin_kicad_pcb.Component(
	footprint="Pin_Headers:Pin_Header_Straight_1x02_Pitch2.54mm",
	identifier="PIPWR",
	value="Power from Pi",
	pins=[
		Pin(1, "", "3V3_PI"),
		Pin(2, "", "3V3"),
	],
)

fx2_power_jumper = myelin_kicad_pcb.Component(
	footprint="Pin_Headers:Pin_Header_Straight_1x02_Pitch2.54mm",
	identifier="FX2PWR",
	value="Power from FX2",
	pins=[
		Pin(1, "", "3V3_FX2"),
		Pin(2, "", "3V3"),
	],
)

pi_zero = myelin_kicad_pcb.Component(
	footprint="myelin-kicad:raspberry_pi_zero_flipped",
	identifier="PI1",
	value="Raspberry Pi Zero",
	pins=[
		Pin(1, "3V3"),  # left unconnected here because we generate 3v3 onboard
		Pin(2, "5V", ["5V_PI"]),  # TODO remove this?
		Pin(3, "GPIO0-2", ["tube_A1"]),
		Pin(4, "5V", ["5V_PI"]),
		Pin(5, "GPIO1-3", ["tube_A2"]),
		Pin(6, "ser_GND", ["pi_serial_GND"]),
		Pin(7, "GPIO4", ["tube_nRST"]),
		Pin(8, "ser_TX", ["pi_serial_TX"]),
		Pin(9, "GND", ["GND"]),
		Pin(10, "ser_RX", ["pi_serial_RX"]),
		Pin(11, "GPIO17", ["tube_nTUBE"]),
		Pin(12, "GPIO18", ["tube_RnW"]),
		Pin(13, "GPIO21-27", ["tube_A0"]),
		Pin(14, "GND", ["GND"]),
		Pin(15, "GPIO22", ["tube_D4"]),
		Pin(16, "GPIO23", ["tube_D5"]),
		Pin(17, "3V3", ["3V3_PI"]),
		Pin(18, "GPIO24", ["tube_D6"]),
		Pin(19, "GPIO10", ["tube_D2"]),
		Pin(20, "GND", ["GND"]),
		Pin(21, "GPIO9", ["tube_D1"]),
		Pin(22, "GPIO25", ["tube_D7"]),
		Pin(23, "GPIO11", ["tube_D3"]),
		Pin(24, "GPIO8", ["tube_D0"]),
		Pin(25, "GND", ["GND"]),
		Pin(26, "GPIO7", ["tube_PHI0"]),
	],
)

serial_port = myelin_kicad_pcb.Component(
	footprint="Pin_Headers:Pin_Header_Straight_1x03_Pitch2.54mm",
	identifier="SERIAL1",
	value="Pi Serial",
	pins=[
		Pin(1, "GND", ["pi_serial_GND"]),
		Pin(2, "TX", ["pi_serial_TX"]),
		Pin(3, "RX", ["pi_serial_RX"]),
	],
)

# altera jtag header, like in the lc-electronics xc9572xl board
# left column: tck tdo tms nc tdi
# right column: gnd vcc nc nc gnd
cpld_jtag = myelin_kicad_pcb.Component(
    footprint="Pin_Headers:Pin_Header_Straight_2x05_Pitch2.54mm",
    identifier="JTAG1",
    value="jtag",
    pins=[
        Pin(1, "TCK", ["cpld_TCK"]), # top left
        Pin(2, "GND", ["GND"]), # top right
        Pin(3, "TDO", ["cpld_TDO"]),
        Pin(4, "3V3", ["3V3"]),
        Pin(5, "TMS", ["cpld_TMS"]),
        Pin(6, "NC"),
        Pin(7, "NC"),
        Pin(8, "NC"),
        Pin(9, "TDI", ["cpld_TDI"]),
        Pin(10, "GND", ["GND"]),
    ],
)

# TODO extpwr header

# TODO switch analyzer over to using 3v3 versions of all signals.

# TODO reset level conversion using diode + pullup

# DONE lcsoft mini footprint.  need to flip it to look like this, so the lcsoft
# mini board can plug in to the top of the cartridge.

#   R2 R1       L2 L1
#   R4 R3       L4 L3
#    ...         ...
#  R20 R19     L20 L19

# TODO double check against real lcsoft PCB

analyzer = myelin_kicad_pcb.Component(
    footprint="myelin-kicad:lcsoft_mini_flipped",
    identifier="CONN",
    value="lcsoft mini",
    pins=[
        # left side, top to bottom, left to right, with board face up
        # and USB socket upward
        Pin( "L1", "PD5", "cpu_nNMI"),  # TODO add header for BBC test clip  **not on pi
        Pin( "L2", "PD6", "cpu_nRST"),
        Pin( "L3", "PD7", "cpu_A0"),
        Pin( "L4", "GND", "GND"),
        Pin( "L5", "CLK"),
        Pin( "L6", "GND", "GND"),
        Pin( "L7", "RDY0"),  # TODO tie to 3V3 via 1k resistor
        Pin( "L8", "RDY1", "cpu_CLK_jumper"),  # TODO add jumper to cpu_CLK
        Pin( "L9", "GND", "GND"),
        Pin("L10", "GND", "GND"),
        Pin("L11", "GND", "GND"),
        Pin("L12", "FCLK"),
        Pin("L13", "SCL"),
        Pin("L14", "SDA"),
        Pin("L15", "PB0", "cpu_D0"),
        Pin("L16", "PB1", "cpu_D1"),
        Pin("L17", "PB2", "cpu_D2"),
        Pin("L18", "PB3", "cpu_D3"),
        Pin("L19", "3V3", "3V3_FX2"),  # generated from USB
        Pin("L20", "3V3", "3V3_FX2"),  # generated from USB

        # right side, top to bottom, left to right
        Pin( "R1", "PD4", "cpu_nIRQ"),  # **not on pi
        Pin( "R2", "PD3", "cpu_CLK"),
        Pin( "R3", "PD2", "cpu_READY"),  # TODO add header for BBC test clip **not on pi
        Pin( "R4", "PD1", "cpu_SYNC"),  # TODO add header for test clip **not on pi
        Pin( "R5", "PD0", "cpu_RnW"),  # TODO add header to switch Elk/Master
        Pin( "R6", "PA7"),
        Pin( "R7", "PA6", "analyzer_PA6"),  # tie to 3V3 via 1k resistor
        Pin( "R8", "PA5", "analyzer_PA5"),  # tie to 3V3 via 1k resistor
        Pin( "R9", "PA4", "analyzer_PA4"),  # tie to GND via 1k resistor
        Pin("R10", "PA3"),
        Pin("R11", "PA2", "analyzer_PA2"),  # tie to 3V3 via 1k resistor
        Pin("R12", "PA1"),
        Pin("R13", "PA0"),
        Pin("R14", "CTL2"),
        Pin("R15", "CTL1"),
        Pin("R16", "CTL0"),
        Pin("R17", "PB7", "cpu_D7"),
        Pin("R18", "PB6", "cpu_D6"),
        Pin("R19", "PB5", "cpu_D5"),
        Pin("R20", "PB4", "cpu_D4"),
    ],
)
pull_resistors = [
    myelin_kicad_pcb.R0805("1k", "analyzer_PA6", "3V3", ref="R1"),
    myelin_kicad_pcb.R0805("1k", "analyzer_PA5", "3V3", ref="R2"),
    myelin_kicad_pcb.R0805("1k", "analyzer_PA4", "GND", ref="R3"),
    myelin_kicad_pcb.R0805("1k", "analyzer_PA2", "3V3", ref="R4"),
]

for n in range(20):
    single_staple = myelin_kicad_pcb.Component(
        footprint="myelin-kicad:via_single",
        identifier="staple_single%d" % (n+1),
        value="",
        pins=[Pin(1, "GND", ["GND"])],
    )

myelin_kicad_pcb.dump_netlist("fx2_tube_cartridge_adapter.net")
