$(info $(shell \
	cp -v ../../a3000_rom_emulator/os_switcher_bootloader/keyboard.cc \
	      ../../a3000_rom_emulator/os_switcher_bootloader/keyboard.h .))

BOARD_TAG = leonardo
include ../../third_party/Arduino-Makefile/Arduino.mk
